### ISSUE TITLE
Adding cases TextView next to region name inside Spinner

### ISSUE THREAD

**Issue by suudupa** [suudupa/Coronavirus_Tracker#48]
Need to refactor code (i.e. rebuilding region list).

**Comment by RK360** [comment]
Does this also include the bug where refreshing the list brings you back to world instead of the selected region? This issue came up after we changed the spinner

**Comment by suudupa** [comment]
> Does this also include the bug where refreshing the list brings you back to world instead of the selected region? This issue came up after we changed the spinner.

@RK360, yep, code hasn't been refactored yet.

**Comment by suudupa** [comment]
Feature implemented and bug fixed. Spinner is no longer searchable (to be seen in #24).
